### ISSUE TITLE
Lots of errors in Console and possebly Memory Leak

### ISSUE THREAD

**Issue by Lars-Thestorf** [WOLFI3654/SpigotTNTTracer#4]
I put the plugin on my (Paper)Spigot Server but it seems to do a lot of trouble
In Console of the Server are lots of the following errormessage:

`Could not pass event EntityExplodeEvent to TntTracer v1.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.12.jar:git-Paper-1124]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.jar:git-Paper-1124]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.jar:git-Paper-1124]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [patched_1.12.jar:git-Paper-1124]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [patched_1.12.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.Explosion.a(Explosion.java:201) [patched_1.12.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.World.createExplosion(World.java:2019) [patched_1.12.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.WorldServer.createExplosion(WorldServer.java:1243) [patched_1.12.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.EntityTNTPrimed.explode(EntityTNTPrimed.java:101) [patched_1.12.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.EntityTNTPrimed.B_(EntityTNTPrimed.java:81) [patched_1.12.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1748) [patched_1.12.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1718) [patched_1.12.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1535) [patched_1.12.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:668) [patched_1.12.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:910) [patched_1.12.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) [patched_1.12.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [patched_1.12.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [patched_1.12.jar:git-Paper-1124]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
	at de.wolfi.tnttracer.ListenerInstance.onExplode(ListenerInstance.java:55) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor236.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.12.jar:git-Paper-1124]
	... 18 more`
and also the plugin seems to use more and more RAM the longer it runs

**Comment by WOLFI3654** [comment]
@Lars-Thestorf Okay. Can you please send me a list of all your installed plugins?

**Comment by WOLFI3654** [comment]
@Lars-Thestorf Just to be sure.

But I'll have a look around my code and work a bit on it.

**Comment by Lars-Thestorf** [comment]
I dont realy know why but sure:
Plugins (14): HiveJumpPads, FastAsyncWorldEdit, Essentials, PermissionsEx, TntTracer, SpawnPlugin (Self coded), F3NPerm, ProtocolLib, Multiverse-Core, WorldEdit, schematicmanager (Self coded), ServerListPlus, CommandSigns, WorldGuard

**Comment by WOLFI3654** [comment]
@Lars-Thestorf have you called /hide after calling /show ?
this could be your RAM issue

**Comment by WOLFI3654** [comment]
So I updated the plugin. You may try out the hotfix. This should solve the NullPointerException

**Comment by Lars-Thestorf** [comment]
Awesome im not able to reproduce that error in the new version thanks for the realy fast fix :D

**Comment by WOLFI3654** [comment]
@Lars-Thestorf And keep in mind. Hide your trail after showing it
